In [2]:
import espaloma as esp

In [3]:
g = esp.Graph.load("g_tr/0")

Using backend: pytorch


In [15]:
g.nodes['n1'].data['q']

tensor([[ 0.4409],
        [ 0.0389],
        [-0.1576],
        [-0.1930],
        [ 0.1201],
        [-0.1602],
        [ 0.5209],
        [ 0.5994],
        [-0.1971],
        [-0.6563],
        [-0.5609],
        [-0.5036],
        [-0.0623],
        [-0.1187],
        [ 0.0414],
        [ 0.1781],
        [ 0.0655],
        [ 0.0655],
        [ 0.0655],
        [ 0.4735]], dtype=torch.float64)

In [13]:
esp.mm.

In [12]:
print(u)

tensor([[-0.0824, -0.0847, -0.0872, -0.0851, -0.0829, -0.0842, -0.0840, -0.0840,
         -0.0837, -0.0837, -0.0837, -0.0837, -0.0837, -0.0837, -0.0838, -0.0837,
         -0.0837, -0.0835, -0.0833, -0.0834, -0.0833, -0.0833, -0.0833, -0.0833,
         -0.0833, -0.0833, -0.0833, -0.0833, -0.0833, -0.0833, -0.0833, -0.0833,
         -0.0833, -0.0833, -0.0833, -0.0833, -0.0833, -0.0833, -0.0833, -0.0833,
         -0.0833, -0.0833, -0.0833, -0.0833, -0.0834, -0.0834, -0.0834, -0.0834,
         -0.0834, -0.0834, -0.0834, -0.0834, -0.0834, -0.0834, -0.0834, -0.0834,
         -0.0834, -0.0834, -0.0834, -0.0834, -0.0834, -0.0834, -0.0834, -0.0834,
         -0.0834, -0.0834, -0.0834, -0.0834, -0.0834, -0.0834, -0.0834, -0.0834,
         -0.0834]], dtype=torch.float64)


In [14]:
print(u)

tensor([[-0.0824, -0.0847, -0.0872, -0.0851, -0.0829, -0.0842, -0.0840, -0.0840,
         -0.0837, -0.0837, -0.0837, -0.0837, -0.0837, -0.0837, -0.0838, -0.0837,
         -0.0837, -0.0835, -0.0833, -0.0834, -0.0833, -0.0833, -0.0833, -0.0833,
         -0.0833, -0.0833, -0.0833, -0.0833, -0.0833, -0.0833, -0.0833, -0.0833,
         -0.0833, -0.0833, -0.0833, -0.0833, -0.0833, -0.0833, -0.0833, -0.0833,
         -0.0833, -0.0833, -0.0833, -0.0833, -0.0834, -0.0834, -0.0834, -0.0834,
         -0.0834, -0.0834, -0.0834, -0.0834, -0.0834, -0.0834, -0.0834, -0.0834,
         -0.0834, -0.0834, -0.0834, -0.0834, -0.0834, -0.0834, -0.0834, -0.0834,
         -0.0834, -0.0834, -0.0834, -0.0834, -0.0834, -0.0834, -0.0834, -0.0834,
         -0.0834]], dtype=torch.float64)


In [8]:
g.mol.partial_charges

Quantity(value=array([ 0.4409    ,  0.03893   , -0.15764999, -0.19296999,  0.12012   ,
       -0.16024999,  0.52085   ,  0.59938002, -0.19707   , -0.65627998,
       -0.56093001, -0.50362003, -0.06228   , -0.11871   ,  0.04138   ,
        0.17806999,  0.06553   ,  0.06553   ,  0.06553   ,  0.47354001]), unit=elementary charge)